# Generated by Django 3.2.9 on 2021-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_projectavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ProjectAvatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
