# Generated by Django 3.2.9 on 2021-11-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_projectavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectAvatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
