# Generated by Django 3.2.9 on 2021-11-15 16:17

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_projectavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ProjectAvatar',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='project_manager_app'),
        ),
    ]
